/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ekin_samplejni_SampleJni */

#ifndef _Included_com_example_ekin_samplejni_SampleJni
#define _Included_com_example_ekin_samplejni_SampleJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ekin_samplejni_SampleJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ekin_samplejni_SampleJni_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
